import { createTheme } from '@mui/material/styles';

export const colors = {
  primary: '#1F5FBF', onPrimary: '#FFFFFF', secondaryContainer: '#D8E4FA',
  onSecondaryContainer: '#0F2A57', iconContainer: '#DDE8FA',
  canvas: '#EDF1F8', paper: '#FFFFFF', surface: '#F3F6FB', surfaceHover: '#E9EEF7',
  container: '#EEF2F9', outline: '#717785', outlineVariant: '#C1C7D2',
  subtle: '#717785', divider: '#E3E8F1', error: '#BA1A1A', saveBar: '#2B2F37',
  sea: '#1F5FBF', deep: '#0F2A57', ink: '#181C23', muted: '#434753', fog: '#DDE3EE',
};
const fontFamily = '"Manrope Variable", "Noto Sans SC Variable", "Segoe UI", sans-serif';

export const theme = createTheme({
  breakpoints: { values: { xs: 0, sm: 600, md: 840, lg: 1200, xl: 1536 } },
  palette: {
    mode: 'light',
    primary: { main: colors.primary, dark: '#1A52A6', contrastText: colors.onPrimary },
    secondary: { main: colors.deep, light: colors.secondaryContainer },
    background: { default: colors.canvas, paper: colors.paper },
    text: { primary: colors.ink, secondary: colors.muted },
    divider: colors.divider,
    success: { main: '#2E7D4F', light: '#CDEBD6', dark: '#0D4F2B' },
    warning: { main: '#A86B00', light: '#FDE3B8', dark: '#5C3C00' },
    error: { main: colors.error, light: '#FFDAD6', dark: '#8C1D18' },
    info: { main: colors.primary, light: colors.secondaryContainer, dark: colors.deep },
  },
  shape: { borderRadius: 8 },
  typography: {
    fontFamily,
    h1: { fontSize: '1.375rem', fontWeight: 500, lineHeight: '28px' },
    h2: { fontSize: '1.375rem', fontWeight: 500, lineHeight: '28px' },
    h3: { fontSize: '1rem', fontWeight: 600, lineHeight: '24px' },
    h4: { fontSize: '1rem', fontWeight: 600, lineHeight: '24px' },
    h5: { fontSize: '1rem', fontWeight: 600, lineHeight: '24px' },
    h6: { fontSize: '1rem', fontWeight: 600, lineHeight: '24px' },
    body1: { fontSize: '0.875rem', lineHeight: '20px' },
    body2: { fontSize: '0.8125rem', lineHeight: '20px' },
    caption: { fontSize: '0.75rem', lineHeight: '16px' },
    button: { textTransform: 'none', fontSize: '0.8125rem', fontWeight: 600, letterSpacing: 0 },
    overline: { fontSize: '0.75rem', lineHeight: '16px', fontWeight: 600, letterSpacing: '0.03em' },
  },
  components: {
    MuiButton: { defaultProps: { disableElevation: true }, styleOverrides: {
      root: { borderRadius: 20, minHeight: 40, paddingInline: 20, flexShrink: 0 },
      sizeSmall: { minHeight: 36, paddingInline: 16, fontSize: 12 },
      outlined: { borderColor: colors.outlineVariant },
      startIcon: { '& > *:nth-of-type(1)': { fontSize: 18 } },
    } },
    MuiIconButton: { styleOverrides: { root: { width: 40, height: 40, color: colors.muted } } },
    MuiOutlinedInput: { styleOverrides: { root: { borderRadius: 4, '& .MuiOutlinedInput-notchedOutline': { borderColor: colors.outline } } } },
    MuiInputLabel: { styleOverrides: { root: { fontSize: 14 } } },
    MuiFormHelperText: { styleOverrides: { root: { fontSize: 12, marginLeft: 0 } } },
    MuiPaper: { defaultProps: { elevation: 0 }, styleOverrides: { root: { backgroundImage: 'none' }, outlined: { borderColor: colors.fog, borderRadius: 20 } } },
    MuiChip: { styleOverrides: {
      root: { fontSize: 12, fontWeight: 500, borderRadius: 8, height: 28, backgroundColor: '#E4E8F0', color: colors.muted, borderColor: 'transparent' },
      sizeSmall: { height: 24, borderRadius: 6, fontSize: 11 },
      colorSuccess: { backgroundColor: '#CDEBD6', color: '#0D4F2B' },
      colorWarning: { backgroundColor: '#FDE3B8', color: '#5C3C00' },
      colorError: { backgroundColor: '#FFDAD6', color: '#8C1D18' },
      colorInfo: { backgroundColor: colors.secondaryContainer, color: colors.deep },
      colorPrimary: { backgroundColor: colors.secondaryContainer, color: colors.deep },
    } },
    MuiTableContainer: { styleOverrides: { root: { borderRadius: 20 } } },
    MuiTableCell: { styleOverrides: {
      root: { borderColor: '#EEF1F7', padding: '16px 24px', fontSize: 13 },
      head: { color: colors.muted, backgroundColor: '#F6F8FC', borderColor: '#E6EBF3', fontSize: 12, fontWeight: 600, paddingBlock: 12, whiteSpace: 'nowrap' },
    } },
    MuiTableRow: { styleOverrides: { root: { '&:last-child td': { borderBottom: 0 }, '&:hover': { backgroundColor: '#F7F9FD' } } } },
    MuiAlert: { styleOverrides: { root: { borderRadius: 12, fontSize: 13 } } },
    MuiLinearProgress: { styleOverrides: {
      root: { height: 6, borderRadius: 3, backgroundColor: '#DCE4F2' },
      bar: { borderRadius: 3 },
      indeterminate: { '@media (prefers-reduced-motion: reduce)': {
        '& .MuiLinearProgress-bar1': { animation: 'none', left: '32.5%', width: '35%', transform: 'none' },
        '& .MuiLinearProgress-bar2': { display: 'none' },
      } },
    } },
    MuiDialog: { styleOverrides: { paper: { borderRadius: 28, backgroundColor: colors.container, boxShadow: '0 12px 32px rgba(0,0,0,.2)', margin: 16 } } },
    MuiDialogTitle: { styleOverrides: { root: { fontSize: 24, lineHeight: '32px', fontWeight: 500, padding: '24px 24px 16px' } } },
    MuiDialogContent: { styleOverrides: { root: { paddingInline: 24 } } },
    MuiDialogActions: { styleOverrides: { root: { padding: '16px 24px 24px', gap: 8 } } },
    MuiBackdrop: { styleOverrides: { root: { backgroundColor: 'rgba(10,16,30,.36)' } } },
    MuiMenu: { styleOverrides: { paper: { backgroundColor: colors.container, borderRadius: 12, boxShadow: '0 4px 12px rgba(0,0,0,.14), 0 1px 3px rgba(0,0,0,.1)' } } },
    MuiMenuItem: { styleOverrides: { root: { minHeight: 44, fontSize: 13 } } },
    MuiTabs: { styleOverrides: { root: { minHeight: 48 }, indicator: { height: 3, backgroundColor: 'transparent', '&::after': { content: '""', position: 'absolute', inset: '0 16px', backgroundColor: colors.primary, borderRadius: '3px 3px 0 0' } } } },
    MuiTab: { styleOverrides: { root: { minHeight: 48, minWidth: 0, padding: '12px 16px', textTransform: 'none', fontSize: 14, fontWeight: 500, color: colors.muted, '&.Mui-selected': { fontWeight: 600 }, '&:hover': { backgroundColor: 'rgba(24,28,35,.05)' } } } },
    MuiToggleButtonGroup: { styleOverrides: { root: { borderRadius: 20 } } },
    MuiToggleButton: { styleOverrides: { root: { minHeight: 40, borderColor: colors.outline, borderRadius: 20, textTransform: 'none', padding: '8px 20px', fontSize: 13, lineHeight: '20px', '&.Mui-selected': { color: colors.deep, backgroundColor: colors.secondaryContainer, '&:hover': { backgroundColor: '#C7D8F5' } } } } },
    MuiSwitch: { styleOverrides: {
      root: { width: 60, height: 40, padding: 4 },
      switchBase: { padding: 12, '&.Mui-checked': { transform: 'translateX(20px)', padding: 8, '& + .MuiSwitch-track': { backgroundColor: colors.primary, opacity: 1, border: 0 }, '& .MuiSwitch-thumb': { backgroundColor: 'white', width: 24, height: 24 } } },
      thumb: { boxShadow: 'none', width: 16, height: 16, backgroundColor: colors.outline },
      track: { borderRadius: 16, border: `2px solid ${colors.outline}`, backgroundColor: '#E4E8F0', opacity: 1 },
    } },
  },
});
