package media

import (
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"errors"
)

type DiagnosticSampleKind string

const (
	DiagnosticRawVideo             DiagnosticSampleKind = "raw-yuv420p-v1"
	DiagnosticRawAudio             DiagnosticSampleKind = "raw-pcm-s16le-v1"
	DiagnosticH264                 DiagnosticSampleKind = "prepared-h264-v1"
	DiagnosticAAC                  DiagnosticSampleKind = "prepared-aac-adts-v1"
	DiagnosticWidth                                     = 320
	DiagnosticHeight                                    = 192
	DiagnosticVideoFrames                               = 8
	DiagnosticFrameRate                                 = 8
	DiagnosticVideoFrameBytes                           = DiagnosticWidth * DiagnosticHeight * 3 / 2
	DiagnosticVideoBytes                                = DiagnosticVideoFrameBytes * DiagnosticVideoFrames
	DiagnosticSampleRate                                = 48000
	DiagnosticAudioChannels                             = 2
	DiagnosticAudioSampleFrames                         = 8192
	DiagnosticAudioBytes                                = DiagnosticAudioSampleFrames * DiagnosticAudioChannels * 2
	DiagnosticCompressedBytesLimit                      = 1 << 20
)

var ErrDiagnosticSample = errors.New("invalid fixed diagnostic sample")

// DiagnosticSampleSpec describes a fixed, versioned fixture, never an arbitrary
// media input. Compressed sizes and decoded AAC lengths require actual future
// preparation records; zero ExactBytes is not an attestation about their size.
type DiagnosticSampleSpec struct {
	Kind                DiagnosticSampleKind
	Format              string
	PixelFormat         string
	Width               int
	Height              int
	VideoFrames         int
	FrameRate           int
	SampleRate          int
	Channels            int
	AudioSampleFrames   int
	ExactBytes          int
	MaximumBytes        int
	RequiresPreparation bool
}

// DiagnosticRawSample owns a fresh byte slice on every call. SHA256 describes
// those generated bytes only, not a file, encoder result, or hardware test.
type DiagnosticRawSample struct {
	Spec   DiagnosticSampleSpec
	Data   []byte
	SHA256 string
}

func DiagnosticSampleSpecification(kind DiagnosticSampleKind) (DiagnosticSampleSpec, error) {
	spec := DiagnosticSampleSpec{Kind: kind}
	switch kind {
	case DiagnosticRawVideo, DiagnosticH264:
		spec.Width, spec.Height = DiagnosticWidth, DiagnosticHeight
		spec.VideoFrames, spec.FrameRate = DiagnosticVideoFrames, DiagnosticFrameRate
		spec.PixelFormat = "yuv420p"
		if kind == DiagnosticRawVideo {
			spec.Format, spec.ExactBytes = "rawvideo", DiagnosticVideoBytes
			spec.MaximumBytes = spec.ExactBytes
		} else {
			spec.Format, spec.RequiresPreparation = "h264", true
			spec.MaximumBytes = DiagnosticCompressedBytesLimit
		}
	case DiagnosticRawAudio, DiagnosticAAC:
		spec.SampleRate, spec.Channels = DiagnosticSampleRate, DiagnosticAudioChannels
		if kind == DiagnosticRawAudio {
			spec.Format, spec.AudioSampleFrames = "s16le", DiagnosticAudioSampleFrames
			spec.ExactBytes, spec.MaximumBytes = DiagnosticAudioBytes, DiagnosticAudioBytes
		} else {
			spec.Format, spec.RequiresPreparation = "aac", true
			spec.MaximumBytes = DiagnosticCompressedBytesLimit
		}
	default:
		return DiagnosticSampleSpec{}, ErrDiagnosticSample
	}
	return spec, nil
}

// GenerateDiagnosticSample creates only uncompressed fixtures. Prepare H264
// and AAC using an actual software encode, then retain the resulting file's
// identity, bytes and software-decoded reference before dependent stages run.
func GenerateDiagnosticSample(kind DiagnosticSampleKind) (DiagnosticRawSample, error) {
	spec, err := DiagnosticSampleSpecification(kind)
	if err != nil || spec.RequiresPreparation {
		return DiagnosticRawSample{}, ErrDiagnosticSample
	}
	data := make([]byte, spec.ExactBytes)
	if kind == DiagnosticRawVideo {
		generateDiagnosticVideo(data)
	} else {
		generateDiagnosticAudio(data)
	}
	digest := sha256.Sum256(data)
	return DiagnosticRawSample{Spec: spec, Data: data, SHA256: hex.EncodeToString(digest[:])}, nil
}

func generateDiagnosticVideo(data []byte) {
	const lumaBytes = DiagnosticWidth * DiagnosticHeight
	const chromaWidth, chromaHeight = DiagnosticWidth / 2, DiagnosticHeight / 2
	for frame := 0; frame < DiagnosticVideoFrames; frame++ {
		start := frame * DiagnosticVideoFrameBytes
		for y := 0; y < DiagnosticHeight; y++ {
			for x := 0; x < DiagnosticWidth; x++ {
				luma := byte(16 + ((x/40+y/24+frame*2)%8)*24)
				// A moving, high-contrast block distinguishes frame order without
				// relying on a font, locale, random generator, or floating point.
				if x >= frame*32 && x < frame*32+32 && y >= 80 && y < 112 {
					luma = 235
				}
				data[start+y*DiagnosticWidth+x] = luma
			}
		}
		for y := 0; y < chromaHeight; y++ {
			for x := 0; x < chromaWidth; x++ {
				position := y*chromaWidth + x
				data[start+lumaBytes+position] = byte(16 + ((x/20+frame)%8)*28)
				data[start+lumaBytes+lumaBytes/4+position] = byte(16 + ((y/12+frame*3)%8)*28)
			}
		}
	}
}

func generateDiagnosticAudio(data []byte) {
	triangle := func(position, period int) int {
		phase := position % period
		if phase < period/2 {
			return -12000 + phase*48000/period
		}
		return 36000 - phase*48000/period
	}
	for frame := 0; frame < DiagnosticAudioSampleFrames; frame++ {
		gain := min(frame, DiagnosticAudioSampleFrames-1-frame, 128)
		left := int16(triangle(frame, 48) * gain / 128)
		right := int16(triangle(frame+16, 64) * gain / 128)
		position := frame * DiagnosticAudioChannels * 2
		binary.LittleEndian.PutUint16(data[position:], uint16(left))
		binary.LittleEndian.PutUint16(data[position+2:], uint16(right))
	}
}
