package media

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"errors"
	"testing"
)

func TestDiagnosticVideoHasEightDistinctPlanarBoundedFrames(t *testing.T) {
	sample, err := GenerateDiagnosticSample(DiagnosticRawVideo)
	if err != nil || len(sample.Data) != 737280 || sample.Spec.Width != 320 || sample.Spec.Height != 192 ||
		sample.Spec.VideoFrames != 8 || sample.Spec.FrameRate != 8 || sample.Spec.Format != "rawvideo" || sample.Spec.PixelFormat != "yuv420p" {
		t.Fatalf("fixed raw video shape is incorrect: %v", err)
	}
	const luma, plane, frameBytes = 320 * 192, 160 * 96, 320 * 192 * 3 / 2
	seen := make(map[[32]byte]bool)
	for frame := 0; frame < 8; frame++ {
		data := sample.Data[frame*frameBytes : (frame+1)*frameBytes]
		digest := sha256.Sum256(data)
		if seen[digest] {
			t.Fatal("fixed video cannot distinguish frame order")
		}
		seen[digest] = true
		for index, value := range data {
			upper := byte(235)
			if index >= luma {
				upper = 240
			}
			if value < 16 || value > upper {
				t.Fatal("raw video left its fixed limited-range planes")
			}
		}
		if data[80*320+frame*32] != 235 || len(data[luma:luma+plane]) != plane || len(data[luma+plane:]) != plane {
			t.Fatal("moving frame marker or chroma-plane layout changed")
		}
	}
	if sample.Data[0] != 16 || sample.Data[luma] != 16 || sample.Data[luma+plane] != 16 ||
		sample.Data[frameBytes] != 64 || sample.Data[frameBytes+luma] != 44 || sample.Data[frameBytes+luma+plane] != 100 {
		t.Fatal("the versioned Y, U, V plane witness changed")
	}
}

func TestDiagnosticAudioIsFiniteStereoSignedLittleEndianPCM(t *testing.T) {
	sample, err := GenerateDiagnosticSample(DiagnosticRawAudio)
	if err != nil || len(sample.Data) != 32768 || sample.Spec.SampleRate != 48000 || sample.Spec.Channels != 2 ||
		sample.Spec.AudioSampleFrames != 8192 || sample.Spec.Format != "s16le" {
		t.Fatalf("fixed raw audio shape is incorrect: %v", err)
	}
	if !bytes.Equal(sample.Data[:8], []byte{0, 0, 0, 0, 0xab, 0xff, 5, 0}) || !bytes.Equal(sample.Data[len(sample.Data)-4:], []byte{0, 0, 0, 0}) {
		t.Fatal("PCM interleaving, signed little-endian values, or edge taper changed")
	}
	var leftEnergy, rightEnergy int64
	different := false
	for frame := 0; frame < 8192; frame++ {
		left := int64(int16(binary.LittleEndian.Uint16(sample.Data[frame*4:])))
		right := int64(int16(binary.LittleEndian.Uint16(sample.Data[frame*4+2:])))
		if left < -12000 || left > 12000 || right < -12000 || right > 12000 {
			t.Fatal("fixed PCM amplitude exceeded its bound")
		}
		leftEnergy += left * left
		rightEnergy += right * right
		different = different || left != right
	}
	if leftEnergy == 0 || rightEnergy == 0 || !different {
		t.Fatal("the fixture is silent or cannot distinguish its two channels")
	}
}

func TestDiagnosticRawSamplesAreDeterministicAndIndependentlyOwned(t *testing.T) {
	for _, kind := range []DiagnosticSampleKind{DiagnosticRawVideo, DiagnosticRawAudio} {
		first, err := GenerateDiagnosticSample(kind)
		if err != nil {
			t.Fatal(err)
		}
		second, err := GenerateDiagnosticSample(kind)
		if err != nil || !bytes.Equal(first.Data, second.Data) || first.SHA256 != second.SHA256 || first.Spec != second.Spec {
			t.Fatal("fixed raw sample generation is not deterministic")
		}
		digest := sha256.Sum256(first.Data)
		if first.SHA256 != hex.EncodeToString(digest[:]) || first.Spec.ExactBytes != len(first.Data) || first.Spec.MaximumBytes != len(first.Data) {
			t.Fatal("raw sample metadata does not describe the generated bytes")
		}
		first.Data[0] ^= 0xff
		third, err := GenerateDiagnosticSample(kind)
		if err != nil || !bytes.Equal(second.Data, third.Data) {
			t.Fatal("a caller changed another sample or the next generated fixture")
		}
	}
}

func TestDiagnosticCompressedSamplesRequireActualPreparation(t *testing.T) {
	for _, kind := range []DiagnosticSampleKind{DiagnosticH264, DiagnosticAAC} {
		spec, err := DiagnosticSampleSpecification(kind)
		if err != nil || !spec.RequiresPreparation || spec.ExactBytes != 0 || spec.MaximumBytes != 1<<20 {
			t.Fatal("compressed fixture metadata invents an encoded size")
		}
		if kind == DiagnosticAAC && spec.AudioSampleFrames != 0 {
			t.Fatal("AAC priming was replaced by a guessed decoded length")
		}
		generated, err := GenerateDiagnosticSample(kind)
		if !errors.Is(err, ErrDiagnosticSample) || len(generated.Data) != 0 || generated.SHA256 != "" {
			t.Fatal("compressed fixture generation fabricated media or evidence")
		}
	}
	for _, kind := range []DiagnosticSampleKind{"", "rawvideo", "http://example.test/input", "../../sample"} {
		if _, err := DiagnosticSampleSpecification(kind); !errors.Is(err, ErrDiagnosticSample) {
			t.Fatal("an unowned sample selector was accepted")
		}
	}
}
