import { stat } from 'node:fs/promises';
import { expect, test } from '@playwright/test';

test('library creation, scanning, task progress, and catalog-only deletion', async ({ page, context }, testInfo) => {
  const name = process.env.GOBY_SMOKE_NAME;
  const password = process.env.GOBY_SMOKE_PASSWORD;
  const mediaPath = process.env.GOBY_SMOKE_MEDIA_PATH;
  const mediaFile = process.env.GOBY_SMOKE_MEDIA_FILE;
  test.skip(!mediaPath || !mediaFile, 'The remote media fixture directory and file are required.');
  if (!name || !password || !mediaPath || !mediaFile) throw new Error('Administrator credentials and media fixtures are required.');
  const originalFile = await stat(mediaFile);
  const pageErrors: string[] = [];
  page.on('pageerror', (error) => pageErrors.push(error.message));

  await page.goto('/admin/libraries');
  await page.getByLabel(/^Username/).fill(name);
  await page.getByLabel(/^Password/).fill(password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Libraries', exact: true })).toBeVisible();
  await expect(page.getByText('Configured media directories', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Create library', exact: true }).first().click();
  const dialog = page.getByRole('dialog', { name: 'Create library', exact: true });
  const libraryName = `Browser library ${Date.now()}`;
  await dialog.getByLabel(/^Library name/).fill(libraryName);
  await dialog.getByLabel(/^Media directories/).fill(mediaPath);
  await dialog.getByRole('checkbox', { name: /^Scan after creating/ }).uncheck();
  await page.screenshot({ path: testInfo.outputPath('create-library-desktop.png'), fullPage: true, animations: 'disabled' });
  const createdResponse = page.waitForResponse((response) => response.request().method() === 'POST' && new URL(response.url()).pathname === '/admin/v1/libraries');
  await dialog.getByRole('button', { name: 'Create library', exact: true }).click();
  expect((await createdResponse).status()).toBe(201);
  await expect(dialog).not.toBeVisible();
  const libraryCard = page.getByRole('list', { name: 'Media libraries' }).getByRole('listitem').filter({ has: page.getByRole('heading', { name: libraryName, exact: true }) });
  await expect(libraryCard).toBeVisible();
  await expect(libraryCard.getByText('Last scan: Not scanned yet', { exact: true })).toBeVisible();

  const scanResponse = page.waitForResponse((response) => response.request().method() === 'POST' && /\/admin\/v1\/libraries\/[^/]+\/scan$/.test(new URL(response.url()).pathname));
  await libraryCard.getByRole('button', { name: 'Scan library', exact: true }).click();
  const started = await scanResponse;
  expect(started.status()).toBe(202);
  const scan = await started.json() as { Job: { Id: string; LibraryId: string } };
  let taskRequests = 0;
  page.on('request', (request) => {
    if (request.method() === 'GET' && new URL(request.url()).pathname === '/admin/v1/jobs') taskRequests += 1;
  });
  await page.getByRole('link', { name: 'Tasks', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Tasks', exact: true })).toBeVisible();
  const task = page.locator(`[data-job-id="${scan.Job.Id}"]`);
  await expect(task.getByText('Completed', { exact: true })).toBeVisible({ timeout: 45_000 });
  await expect(task.getByText('Scanned', { exact: true })).toBeVisible();
  await expect(task.getByText('Added', { exact: true })).toBeVisible();
  const jobsResponse = await context.request.get('/admin/v1/jobs');
  expect(jobsResponse.status()).toBe(200);
  const jobs = await jobsResponse.json() as { Items: { Id: string; Status: string; Scanned: number; Added: number }[] };
  const completedJob = jobs.Items.find((job) => job.Id === scan.Job.Id);
  expect(completedJob?.Status).toBe('completed');
  expect(completedJob?.Scanned).toBeGreaterThan(0);
  expect(completedJob?.Added).toBeGreaterThan(0);
  await expect(page.getByText('No active scans.', { exact: true })).toBeVisible();
  const requestsAfterCompletion = taskRequests;
  await page.waitForTimeout(3400);
  expect(taskRequests).toBe(requestsAfterCompletion);
  await page.screenshot({ path: testInfo.outputPath('tasks-desktop.png'), fullPage: true, animations: 'disabled' });

  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('tasks-mobile.png'), fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: 'Open navigation' }).click();
  await page.getByRole('link', { name: 'Libraries', exact: true }).click();
  await expect(libraryCard).toBeVisible();
  await expect(page.locator('#main-content')).toBeFocused();
  await expect(libraryCard.getByText('Last scan: Not scanned yet', { exact: true })).not.toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('libraries-mobile.png'), fullPage: true, animations: 'disabled' });
  await expect(page.locator('#main-content')).toBeFocused();
  await expect(page.getByRole('link', { name: 'Skip to content' })).not.toBeFocused();
  await libraryCard.getByRole('button', { name: 'Delete', exact: true }).click();
  const removeDialog = page.getByRole('dialog', { name: 'Delete library?' });
  await expect(removeDialog.getByText('This removes the library and its catalog records from Goby. Media files on disk will not be deleted.', { exact: true })).toBeVisible();
  const removed = page.waitForResponse((response) => response.request().method() === 'DELETE' && new URL(response.url()).pathname === `/admin/v1/libraries/${scan.Job.LibraryId}`);
  await removeDialog.getByRole('button', { name: 'Delete library', exact: true }).click();
  expect((await removed).status()).toBe(204);
  await expect(libraryCard).not.toBeVisible();
  const retainedFile = await stat(mediaFile);
  expect(retainedFile.isFile()).toBe(true);
  expect(retainedFile.size).toBe(originalFile.size);
  expect(retainedFile.mtimeMs).toBe(originalFile.mtimeMs);
  console.log(JSON.stringify({ pageErrors, scanned: completedJob?.Scanned, added: completedJob?.Added, mediaFilePreserved: true }));
  expect(pageErrors).toEqual([]);
});

test('an active scan can be cancelled from the task page', async ({ page, context }, testInfo) => {
  const name = process.env.GOBY_SMOKE_NAME;
  const password = process.env.GOBY_SMOKE_PASSWORD;
  const cancelPath = process.env.GOBY_SMOKE_CANCEL_MEDIA_PATH;
  if (!name || !password || !cancelPath) throw new Error('Administrator credentials and GOBY_SMOKE_CANCEL_MEDIA_PATH are required for cancellation verification.');
  const pageErrors: string[] = [];
  page.on('pageerror', (error) => pageErrors.push(error.message));

  await page.goto('/admin/libraries');
  await page.getByLabel(/^Username/).fill(name);
  await page.getByLabel(/^Password/).fill(password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('button', { name: 'Create library', exact: true }).first().click();
  const createDialog = page.getByRole('dialog', { name: 'Create library', exact: true });
  const libraryName = `Browser cancel ${Date.now()}`;
  await createDialog.getByLabel(/^Library name/).fill(libraryName);
  await createDialog.getByLabel(/^Media directories/).fill(cancelPath);
  await expect(createDialog.getByRole('checkbox', { name: /^Scan after creating/ })).toBeChecked();
  const createdResponse = page.waitForResponse((response) => response.request().method() === 'POST' && new URL(response.url()).pathname === '/admin/v1/libraries');
  await createDialog.getByRole('button', { name: 'Create library', exact: true }).click();
  const created = await createdResponse;
  expect(created.status()).toBe(201);
  const started = await created.json() as { Library: { Id: string }; Job?: { Id: string } };
  expect(started.Job?.Id).toBeTruthy();
  await expect(createDialog).not.toBeVisible();
  await page.getByRole('link', { name: 'Tasks', exact: true }).click();
  const task = page.locator(`[data-job-id="${started.Job!.Id}"]`);
  await task.getByRole('button', { name: /^Cancel scan for/ }).click();
  const cancelDialog = page.getByRole('dialog', { name: 'Cancel this scan?' });
  await expect(cancelDialog.getByText('Cancelling stops the remaining scan work. Items already scanned remain in the library.', { exact: true })).toBeVisible();
  const cancelledResponse = page.waitForResponse((response) => response.request().method() === 'POST' && new URL(response.url()).pathname === `/admin/v1/jobs/${started.Job!.Id}/cancel`);
  await cancelDialog.getByRole('button', { name: 'Cancel task', exact: true }).click();
  expect((await cancelledResponse).status()).toBe(202);
  await expect(cancelDialog).not.toBeVisible();
  await expect(task.getByText('Cancelled', { exact: true })).toBeVisible({ timeout: 20_000 });
  await expect(task.getByRole('button', { name: /^Cancel scan for/ })).not.toBeVisible();
  const jobsResponse = await context.request.get('/admin/v1/jobs');
  expect(jobsResponse.status()).toBe(200);
  const jobs = await jobsResponse.json() as { Items: { Id: string; Status: string; Scanned: number }[] };
  const cancelledJob = jobs.Items.find((job) => job.Id === started.Job!.Id);
  expect(cancelledJob?.Status).toBe('cancelled');
  await page.screenshot({ path: testInfo.outputPath('task-cancelled-desktop.png'), fullPage: true, animations: 'disabled' });

  await page.getByRole('link', { name: 'Libraries', exact: true }).click();
  const libraryCard = page.getByRole('list', { name: 'Media libraries' }).getByRole('listitem').filter({ has: page.getByRole('heading', { name: libraryName, exact: true }) });
  await libraryCard.getByRole('button', { name: 'Delete', exact: true }).click();
  const removed = page.waitForResponse((response) => response.request().method() === 'DELETE' && new URL(response.url()).pathname === `/admin/v1/libraries/${started.Library.Id}`);
  await page.getByRole('dialog', { name: 'Delete library?' }).getByRole('button', { name: 'Delete library', exact: true }).click();
  expect((await removed).status()).toBe(204);
  await expect(libraryCard).not.toBeVisible();
  const readiness = await context.request.get('/readyz');
  expect(readiness.status()).toBe(200);
  console.log(JSON.stringify({ pageErrors, cancelledFromUI: true, scannedBeforeCancellation: cancelledJob?.Scanned, readinessStatus: readiness.status() }));
  expect(pageErrors).toEqual([]);
});
