ARG BASE=goby-online-base:software
FROM ${BASE}
USER 0:0
COPY --chown=10001:10001 --chmod=0555 goby /usr/local/bin/goby
ARG REVISION
ARG APPLICATION_SHA256
LABEL org.opencontainers.image.revision=${REVISION} io.goby.application.sha256=${APPLICATION_SHA256} io.goby.online-provider-source=${REVISION}
USER 10001:10001
RUN test -x /usr/local/bin/goby && test ! -w /usr/local/bin/goby
